### ISSUE TITLE
local variable 'wentwrong' referenced before assignment

### ISSUE THREAD

**Issue by sobir-git** [pelican-plugins/graphviz#4]
The plugin raises this exception:
```
local variable 'wentwrong' referenced before assignment
```

https://github.com/pelican-plugins/graphviz/blob/d177f9ba45df29dbfc471161726b98077e60e955/pelican/plugins/graphviz/mdx_graphviz.py#L90

**Comment by rlaboiss** [comment]
I just pushed commit 7189c0e that may fix the issue. Could you please test it?

**Comment by sobir-git** [comment]
It didn't fix. I uninstalled the plugin via
```
pip uninstall pelican-graphviz
```

then installed again 
```
pip install --upgrade pelican-graphviz
```

But I could see pip was still using cached version 1.0.0.
Maybe you have to give it a new version and update wheel files?

**Comment by justinmayer** [comment]
@sobir-git We don’t issue releases until the fix has been tested and confirmed to fully address the problem. Rafael was asking you to test what is in the current main branch — not the last release, which is what you got when Pip-installing via the command you wrote above. You can look up directions for Pip-installing from a Git repository, which will allow you to test the fix that Rafael pushed to the main branch.

**Comment by sobir-git** [comment]
Oh sorry about that, I didn't know. So, now I did pip install through git and I can confirm the issue is gone. Thank you!

**Comment by rlaboiss** [comment]
@justinmayer: Thank you for your intervention in this issue. I could not find the documentation for it, but looking at what was done in the plugin repositories, it seems that it is enough to commit a RELEASE.md file containing  "Release type: patch" in order to have version 1.0.1 released. Is there anything else I should pay attention to?

**Comment by rlaboiss** [comment]
Version 1.0.1 of the plugin has been released on PyPI. I am hereby closing this issue.
